pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-cicd-project devops-cicd-project'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop devops-container || true
                docker rm devops-container || true
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d --name devops-container -p 80:80 devops-cicd-project'
            }
        }
    }
}
